#define NABTO_SET_TIME_FROM_ALIVE 0
#define NABTO_LOG_ALL 0
#define NABTO_LOG_SEVERITY_FILTER NABTO_LOG_SEVERITY_LEVEL_TRACE

#define NABTO_CONNECTIONS_SIZE 10
#define NABTO_STREAM_MAX_STREAMS 2
#define NABTO_STREAM_RECEIVE_WINDOW_SIZE 10
//#define NABTO_STREAM_RECEIVE_SEGMENT_SIZE 100